name: CMake Build for Windows & Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install mingw-w64
      run: choco install mingw-w64 --version=13.2.0 -y

    - name: Setup CMake
      uses: lukka/get-cmake@v3.20.0

    - name: Build
      run: cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/
