name: cmake Build for Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y cmake gcc libcjson-dev
          dpkg -L libcjson-dev | grep cJSON.h || (echo "cJSON header not found!" && exit 1)

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build
