name: CMake Build for Windows & Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install mingw-w64
      run: choco install mingw-w64 --version=13.2.0 -y

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y build-essential cmake

    - name: Configure CMake
      run: >
        cmake -G "MinGW Makefiles" -B build
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: compiled-binaries
        path: build/**/*.exe
